# Create a ReadMe.md file (with a Test header) at the given file path.
function Create-TestReadMe ([string]$readMePath) {
    if (!(Test-Path $readMePath))
    {
        New-Item -ItemType "file" -Path $readMePath
    }
    else
    {
        # Clear the contents of the ReadMe file
        Clear-Content -Path $readMePath
    }
    # Add in the header content
    Add-Content -Path $readMePath -Value "# Tests";
    Add-Content -Path $readMePath -Value "";
    Add-Content -Path $readMePath -Value "This document is generated by running the PowerShell script (using PowerShell ISE).";
    Add-Content -Path $readMePath -Value "";
    Add-Content -Path $readMePath -Value "Page or View | Test Path | Description | Test Name";
    Add-Content -Path $readMePath -Value "--- | --- | --- | ---";
}

# Append each test to the read me file
function Append-ReadMe([Object]$tests, [string]$readMePath) {
    foreach ($test in $tests) {
        $page = $test.psobject.properties["Page or View"].value;
        $description = $test.psobject.properties["Description"].value;
        $testPath = $test.psobject.properties["Test Path"].value;
        $testName = $test.psobject.properties["Test Name"].value;
        $readMeLine = $page + " | " + $testPath + " | " + $description + " | " + $testName;
        Add-Content -Path $readMePath -Value $readMeLine;
    }
}
